language: php

php:
    - "7.1"

git:
  depth: 10

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
    - composer install --prefer-dist --no-interaction --no-scripts

script:
    - ./vendor/bin/php-cs-fixer --rules=@PSR2 --dry-run -v fix src
